enkins:
  systemMessage: "Welcome to Jenkins!"

securityRealm:
  local:
    allowsSignup: false
    users:
      - id: "badreddine"
        name: "badreddine"
        password: "Pedro01%%"

authorizationStrategy:
  loggedInUsersCanDoAnything:
    allowAnonymousRead: false

# Change this URL to match your Jenkins URL
jenkinsUrl: "http://localhost:8080/"

# Change this to match the email address for the Jenkins administrator
jenkinsAdminEmail: "badreddineqassimi@gmail.com"

# Change this to match the plugins you want to install
plugins:
  - Configuration as Code
  - Job DSL

  jobs:
    - script: |
        steps {
          shell('df')
        }
        steps{
          shell('echo "Hello dear $NAME!"
                  date
                  echo "This is your DDoS number $BUILD_NUMBER."')
        }
