jenkins:
  jobs:
    - script: |
        steps {
          shell('df')
        }
        steps{
          shell('echo "Hello dear $NAME!"
                  date
                  echo "This is your DDoS number $BUILD_NUMBER."')
        }
