jenkins:
  systemMessage: "Welcome to Jenkins!"
  mode: NORMAL
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "badreddine"
          name: "badreddine"
          password: "${USER_BADREDDINE_PASSWORD}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "badreddine"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "badreddine"

jenkinsUrl: "http://localhost:8080/"

jenkinsAdminEmail: "badreddineqassimi@gmail.com"

plugins:
  - configuration-as-code
  - job-dsl

unclassified:
  jobs:
    - script: |
        pipeline {
          agent any
          stages {
            stage('Print Disk Usage') {
              steps {
                sh 'df -h'
              }
            }
            stage('Print Build Info') {
              steps {
                sh 'echo "Hello dear $NAME!"'
                sh 'date'
                sh 'echo "This is your DDoS number $BUILD_NUMBER."'
              }
            }
          }
        }